# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8d5f1ed8063c6c55d9303af4e1d28ad51b5ab6e359b1484ad3af2374697eba5afbfe29b4984eca91d3042c4a4b5590133779abb7beb03862b6b37d84e264c654

test:
  secret_key_base: 5b292f1cec93aa925a2689dd31e1965f5584394c482724a0502b2a0b56cdd941874985952b68df14b1b84d13df7a33fed9b4af8bbade3ea5a137405384a579fa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
